import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, "..", "..");

/**
 * Lock test: forge-run-ticket capture-discipline contract.
 *
 * `commands/forge-run-ticket.md` is the run protocol the orchestrator obeys.
 * The one-action-per-step agent-output capture rule (dispatch → wait → capture
 * verbatim → parse-agent → continue) must live in the protocol text itself, not
 * only in operator memory. If a future edit drops the discipline phrases — the
 * verbatim-capture sequence, the prohibitions against pre-writing / summarizing /
 * reconstructing / composing / batching, or the halt-don't-repair behavior — this
 * suite goes red so the drift cannot ship silently.
 *
 * We assert on load-bearing phrases (not exact paragraphs) to avoid brittleness
 * on trivial copy edits, mirroring src/agents/charter-output-format.test.ts.
 */

const COMMAND_FILE = join(REPO_ROOT, "commands", "forge-run-ticket.md");

const text = (): string => readFileSync(COMMAND_FILE, "utf8");

const REQUIRED_PHRASES: readonly string[] = [
  // Top-level capture-discipline section exists.
  "Capture discipline",

  // The verbatim-capture sequence (per agent step).
  "dispatch the agent",
  "wait for the actual agent return",
  "verbatim",
  ".forge/<role>-output.yaml",
  "forge parse-agent",
  "continue only after parse succeeds",

  // Prohibitions.
  "pre-writing",
  "summarizing",
  "reconstructing",
  "composing",
  "batching",
  "validating synthesized output",

  // Halt / honest-reporting behavior.
  "AGENT_OUTPUT_INVALID",
  "halt",
  "missing required fields",
  "report fail",
  "report reject",
  "never rewrite an agent response",

  // Bootstrap + verify-install honesty.
  "verify-install",
  "pnpm install-commands",
  "bootstrap",
];

describe("forge-run-ticket capture-discipline contract", () => {
  it("contains the load-bearing capture-discipline phrases", () => {
    const content = text();
    for (const phrase of REQUIRED_PHRASES) {
      expect(content, `missing required phrase: ${phrase}`).toContain(phrase);
    }
  });

  it("requires the verbatim-capture sequence for every agent role", () => {
    const content = text();
    for (const role of ["engineer", "verifier", "pm"]) {
      expect(content, `missing role mention: ${role}`).toContain(role);
    }
  });
});

/**
 * Lock test: forge-run-ticket lock-wiring contract.
 *
 * The epic lock is the *primary* cross-run serialization guarantee for the
 * command orchestrator. That guarantee is only real if the command text actually
 * drives the shipped `forge lock acquire | release | status` surface
 * (src/orchestrator/lock-cli.ts) rather than hand-rolling a non-atomic
 * check-then-write of `lock.json`.
 *
 * This block pins the load-bearing lock-wiring instruction text. The PRESENT
 * assertions prove the new wiring exists (atomic acquire at the top of step 3,
 * owner-checked release on PASS and ESCALATE, hold-across-CORRECT, fail-closed
 * before mutation, never force-break). The ABSENT assertions are the
 * non-tautological half: they prove the old hand-rolled TOCTOU pattern was
 * actually *removed* — the check-then-act `LOCK_EXISTS` pre-check and the bespoke
 * hand-write of the lock JSON (`started_at`) — not merely supplemented. Without
 * the absent half a future edit could re-introduce the race while still passing
 * the present half.
 */

const LOCK_REQUIRED_PHRASES: readonly string[] = [
  // The shipped CLI surface is what serializes the run.
  "forge lock acquire",
  "forge lock release",
  "forge lock status",
  "--run-id",

  // Ownership identity generated by the orchestrator.
  "RUN_ID",
  "crypto.randomUUID()",

  // Collision / corruption verdicts handled fail-closed before any mutation.
  "LOCK_HELD",
  "LOCK_MALFORMED",
  "LOCK_FOREIGN",
  "LOCK_ABSENT",

  // Acquire ordering: before active-ticket emission and before branch creation.
  "before active-ticket emission",
  "before branch creation",
  "before any mutation",

  // Owner-checked release on both terminal outcomes.
  "release",
  "owner-checked",

  // CORRECT keeps the lock held across correction cycles.
  "held across",

  // Never force-break / never steal — stale-recovery is a deferred slice.
  "never force-break",
  "stale-recovery",
  "deferred slice",

  // The carried-forward CAS-window rationale lives where acquire is described.
  "defense-in-depth",
];

const LOCK_FORBIDDEN_PATTERNS: readonly string[] = [
  // The old bespoke hand-write of the lock JSON object.
  "started_at",
  // The old check-then-act existence pre-check.
  "LOCK_EXISTS",
  // The old "rm the lock if stale" recovery hint (no force-clear in this slice).
  "rm the lock",
];

describe("forge-run-ticket lock-wiring contract", () => {
  it("contains the load-bearing lock-wiring phrases", () => {
    const content = text();
    for (const phrase of LOCK_REQUIRED_PHRASES) {
      expect(content, `missing required phrase: ${phrase}`).toContain(phrase);
    }
  });

  it("no longer carries the old hand-rolled lock pattern (non-tautological)", () => {
    const content = text();
    for (const pattern of LOCK_FORBIDDEN_PATTERNS) {
      expect(content, `stale hand-rolled lock pattern still present: ${pattern}`).not.toContain(
        pattern,
      );
    }
  });

  it("acquires the lock before active-ticket emission and before branch creation", () => {
    const content = text();
    const acquireIdx = content.indexOf("forge lock acquire");
    const activeTicketEmitIdx = content.indexOf("active-ticket contract");
    const branchSwitchIdx = content.indexOf("switch -c");
    expect(acquireIdx, "forge lock acquire not found").toBeGreaterThan(-1);
    expect(activeTicketEmitIdx, "active-ticket emission not found").toBeGreaterThan(-1);
    expect(branchSwitchIdx, "branch creation not found").toBeGreaterThan(-1);
    expect(acquireIdx).toBeLessThan(activeTicketEmitIdx);
    expect(acquireIdx).toBeLessThan(branchSwitchIdx);
  });

  it("releases the lock with the matching run_id on PASS and on ESCALATE", () => {
    const content = text();
    // Both terminal paths must call the owner-checked release with --run-id.
    const releaseCount = (
      content.match(/lock release "\$EPIC" --run-id "\$RUN_ID"/g) ?? []
    ).length;
    expect(
      releaseCount,
      "expected owner-checked release on both PASS (step 10) and ESCALATE (step 11)",
    ).toBeGreaterThanOrEqual(2);
  });
});
